---
version: "{build}"
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - bundle install --without benchmarks --path vendor/bundle
build_script:
  - bundle exec rake compile
test_script:
  - '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" --version'
  - >
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -p"Password12!" -e "
    CREATE DATABASE IF NOT EXISTS test;
    CREATE USER '%USERNAME%'@'localhost';
    SET PASSWORD = PASSWORD('');
    FLUSH PRIVILEGES;
    "
  - bundle exec rake spec
# Where do I get Unix find?
#on_failure:
#  - find tmp -name "*.log" -exec cat {};
environment:
  matrix:
    - ruby_version: "23-x64"
    - ruby_version: "23"
    - ruby_version: "22-x64"
    - ruby_version: "22"
    - ruby_version: "21-x64"
    - ruby_version: "21"
    - ruby_version: "200-x64"
    - ruby_version: "200"
cache:
  - vendor
services:
  - mysql
hosts:
  mysql2gem.example.com: 127.0.0.1
